### ISSUE TITLE
Search for item results option

### ISSUE THREAD

**Issue by Dedoooo** [NadyaNayme/TidyChat#15]
![image](https://user-images.githubusercontent.com/93833740/153787890-aafc4753-19f1-4583-aedd-9493701933fb.png)
option to only show location of search item result, when system messages filter is enabled it doesn't show the location of searched item in inventory 

Thank you!

**Comment by NadyaNayme** [comment]
Will be whitelisted in the next version.

**Comment by NadyaNayme** [comment]
Has been added for 0.0.2.13 - will show for your inventory, armoire, glamour dresser, saddlebag, and retainer inventories,
