### ISSUE TITLE
XP filter (and maybe others?) doesn't work in chat if you use abbreviated names

### ISSUE THREAD

**Issue by CerbStarraiser** [NadyaNayme/TidyChat#19]
When set to "Full Name" for chat, the filtering of XP messages works fine.  If you switch to something other than that, you see the XP messages, because at that point instead of saying "You gained XP" it says "Name S. gained XP" and I'm guessing that doesn't match the filter anymore.

![image](https://user-images.githubusercontent.com/65967003/154168958-e08b11ec-32ed-4c4e-b938-fd5bb664bd4e.png)

**Comment by NadyaNayme** [comment]
Fixed in v0.1.0.1 which has just been PR'd and is awaiting approval. Thanks for the report!
