### ISSUE TITLE
Suggestion: Trial Synthesis results

### ISSUE THREAD

**Issue by AcidAshe** [NadyaNayme/TidyChat#37]
It would be very helpful if there were an additional option (in the advanced settings, mayhaps?) to show trial synthesis results when finishing a trial synthesis. Currently they are filtered out.

These are the messages that I am referring to:

![image](https://user-images.githubusercontent.com/33726059/164933884-3efcd2bc-0f02-4a36-92f0-53c938153458.png)

**Comment by NadyaNayme** [comment]
Yea there shouldn't be any issue whitelisting these - but this is going to be the rare case where I group all 3 together under one setting.

It'll be in the Crafting/Gathering tab under `Trial Synthesis Messages` but I don't think I'll be able to add it until later this week or next weekend.

**Comment by NadyaNayme** [comment]
![image](https://user-images.githubusercontent.com/4567166/165878103-da276d02-41f8-40df-a0d0-e9db2fbd06a7.png)

This has been completed and will be included in the next release.

The setting controls the following messages:

- Trial success
- Trial failure
- Quality
- HQ
- Collectability
