### ISSUE TITLE
Suggestion: Option to show Spiritbond messages

### ISSUE THREAD

**Issue by intiv** [NadyaNayme/TidyChat#46]
I really like all the useless messages the system spam option filters out; unfortunately, having it on hides the messages for a piece of gear reaching 100% spiritbond and there is no option to show it.
I usually alt-tab when gathering/crafting so I use these messages to know when a piece reaches 100% spiritbond and also which piece, with the system filter as it is now I have to rely on other plugins to tell me a piece reached full spiritbond but I still have no way of conveniently knowing which piece it was, so I have to constantly check each piece of gear.

**Comment by NadyaNayme** [comment]
> so I have to constantly check each piece of gear.

If you use Extract Materia (the General Command) you don't need to check all your gear. It opens a window and anything at 100% will be at the top of the list.

That being said - this should probably still have a filter and I think it's been suggested before on the Discord but I forgot. So I'll get it added anyways - but you really should use Extract Materia when you get the spiritbonded message. Massive QoL and part of the vanilla game. :)
