### ISSUE TITLE
Filter Suggestion: Unable to execute command outside a PvP area.

### ISSUE THREAD

**Issue by Willshaper** [NadyaNayme/TidyChat#47]
Hi.

I'm playing on Controller, and use the Macro #99 option to use sprint via R3, which requires me to use the same macro for this in both PvE and PvP.

Due to the PvE and PvP Sprint actions being different, it will spam the "Unable to execute command outside a PvP area." whenever I'm not in a PvP area, unless i block all Error Messages.

Therefore I'd like to request a filter addition to the plugin, specifically the option to hide "Unable to execute command outside a PvP area."

**Comment by NadyaNayme** [comment]
Error messages are within the Announcements channel and I won't be filtering anything within Announcements.

Go to Character Config > Log Window Settings > Look for "General" under Log Filters > Announcements > Turn off "Error Messages". Then make sure to include `/macroerror "off"` to get rid of the toast message or use the BurnToast plugin.

```
/macroerror "off"
/macrolock
/action "Sprint"
/pvpaction "Bolt"
/wait 1
/action "Peloton"
/macrocancel
/macroicon "Sprint"
```

This is how I have things setup and I use the above macro (with an `/ac "Mount Roulette"` below `/macrolock` actually) and I receive no spam at all.
