### ISSUE TITLE
[FILTER] Duty Pop

### ISSUE THREAD

**Issue by vasilicious** [NadyaNayme/TidyChat#53]
## Filter Request
add an option to hide the `Duty Pop` system message

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**
![image](https://user-images.githubusercontent.com/45349355/173396857-e979dcdd-7261-4b8c-90f2-0fd96acf88e0.png)
Duty pop: Dohn Mheg

**When does this message happen?**
when duty finder match pop

**Why is it important to see this message?**
would like to hide it instead.

**Comment by NadyaNayme** [comment]
![image](https://user-images.githubusercontent.com/4567166/173451108-c771c9eb-b860-4c00-911f-650b238c1a24.png)
