### ISSUE TITLE
[FILTER] Trust System Notifications

### ISSUE THREAD

**Issue by thakyZ** [NadyaNayme/TidyChat#60]
## Filter Request

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**

> Alisaie attains level 90!
> A new glamour for Alisaie is now available.

![image](https://user-images.githubusercontent.com/950594/179275624-264d72e6-f6e7-4010-9215-bbf67a0360e9.png)

**When does this message happen?**

After you complete a dungeon with the trust system. And only if the story character is due for a level up for that run. The second quote about the glamour is only when they reach a level at an interval of 10 (i.e. 80 and 90).

**Why is it important to see this message?**

Because otherwise there is only an overlaid message in the middle of the screen that can be easily missed, and it would be helpful to keep it in chat. Also, you cannot filter these message without allowing all level up messages for all characters, even those who aren't an NPC.

**Notes:**

I have tried getting this to work on my fork of this plugin's repo, however it was already too late and all my NPCs were level 90, and I can't test it anymore without grinding an alt up to Shadow Bringers.

**Comment by NadyaNayme** [comment]
I saw you working on that in your fork and filtering them out is a bit easier than you had made it. the names of the Trust NPC's are known and static so you don't need to fetch them from the Party-not-actually-Party list that Trust NPC's appear in. These are also System messages and not Progress messages which all other leveling messages (Player and Other Player) go to. So adding two filters for System messages for "attains level" and "a new glamour" would have been enough - if anything the "a new glamour" may overlap with Custom Delivery NPC's but I'm not 100% sure on that and someone who cares about NPC Glamours probably wouldn't mind the overlap.

I'm not sure I understand the value add for this filter though - most people leveling Trusts are leveling them all the way to 90 anyways and when you're starting a new Trust run you see what level everyone has gotten to as well as it being a consistent X dungeons to Y level for each Trust NPC (IIRC). Seeing a Trust attaining level 84 means nothing to me as I either already knew they'd hit 84 that run or I'd see they had hit 84 when selecting Trust NPC's for the next run.

It seems very niche/personal - which is what the Custom Filters feature is meant to be used for.

**Comment by thakyZ** [comment]
Okay, well that's fine, I wanted to put it out there at the very least. Thank you for your feed back 😄
