### ISSUE TITLE
Tippy integration remains enabled after unchecking box

### ISSUE THREAD

**Issue by shaver** [NadyaNayme/TidyChat#61]
I tried Tippy and decided against it, so I unchecked the "Enable integration with Tippy" box. Even after saving config and restarting, I still get periodic messages saying

> [TidyChat] To enable Tippy Tips for Tidy Chat you must first install Tippy.

In case it matters, Tippy is installed but disabled.

**Comment by NadyaNayme** [comment]
Can you close the game client and go to your `%APPDATA%\XivLauncher\PluginConfigs\TidyChat.json` and manually change `EnableTippyTips` from `true  to `false`? Then next time you boot it will be disabled.

The setting in the plugin's config in-game should be doing that when toggled off and everything looks fine in the code and I can't replicate this issue but manually updating your config should resolve the problem.

**Comment by shaver** [comment]
Yep, resolved. Thanks!

**Comment by lovelydumpling** [comment]
I am also having this issue with the newest version.
To try to fix it, I toggled it on, saved, toggled it back off, and saved again.
It was still reporting those messages, so I came here. I logged out of the game and checked TidyChat.json and `EnableTippyTips` is already false. 
I logged back in and the issue did not persist. It would seem that toggling it on and off had the same effect as editing TidyChat.json, including needing a restart for it to take effect.

Although the issue is now resolved for me, I wanted to report this here to show it was not an isolated incident.

**Comment by NadyaNayme** [comment]
Thanks for the report. Honestly it's probably with how the check for Tippy is being done that it requires a restart to actually respect the value. I'm probably missing an "&& EnableTippyTips" somewhere.

**Comment by lovelydumpling** [comment]
It came back suddenly. I logged on and it gave the message. I don't know why. 
This time I checked TidyChat.json without editing the settings in-game at all yet— it's still set to false. 
After continued playtime, it hasn't said it again this run.

I'm mentioning these anomalies in case it helps track the issue down whenever you do look into it.

**Comment by lovelydumpling** [comment]
Do you think we can reopen this issue? I've got no way to stop this from happening, there's nothing to change in TidyChat.json and the notice keeps popping back up seemingly at random when I log in. Sometimes I log in and it acts up until I quit the game, and sometimes it doesn't.

**Comment by NadyaNayme** [comment]
Reopened - but looking back at the code I do check for the config:

> if (Configuration.EnableTippyTips) TippyIpcTips();

Are you 100% sure you're checking the correct configuration file for Tidy Chat?


That being said - I might just remove the Tippy IPC altogether. It was mostly an experiment of me figuring out how IPC for plugins works and I don't think that many people care about Tidy Chat's Tippy messages anyway.

**Comment by lovelydumpling** [comment]
I'm checking `%appdata%\xivlauncher\pluginConfigs\TidyChat.json`

There it reads `"EnableTippyTips": false,`

Unless there's another TidyChat config file elsewhere, this should be the right one.

**Comment by NadyaNayme** [comment]
Tippy IPC has been removed from TidyChat altogether. Couldn't be bothered investigating.

**Comment by lovelydumpling** [comment]
Thank you. Sorry it didn't work out. Hope no one was attached to that feature.
