### ISSUE TITLE
SeString payloads not handled properly by Improved Player Commendations

### ISSUE THREAD

**Issue by sersorrel** [NadyaNayme/TidyChat#69]
some duties (e.g. Tam-Tara, probably Whorleater) have names with "formatting" (including dashes), which gets dropped by TidyChat:

<img width="376" alt="[TidyChat] You received 1 commendation from completing the TamTara Deepcroft (Hard)." src="https://user-images.githubusercontent.com/9433472/235328630-f57aa9a0-ee94-4ea6-aa11-bf2e37fb48d4.png">

this is not a big deal, but it would imo be _nice_ if duty names were displayed with the correct formatting

**Comment by NadyaNayme** [comment]
I pull the duty name straight from the game chat - so it should call it exactly what the game does in chat. I don't adjust any formatting or anything to the names.

https://github.com/NadyaNayme/TidyChat/blob/master/TidyChat/Utility/GetDutyName.cs
