### ISSUE TITLE
Incompatible with 6.5

### ISSUE THREAD

**Issue by GiacomoLaw** [NadyaNayme/TidyChat#73]
Incompatible with v9 api.

**Comment by NadyaNayme** [comment]
Infi did a huge favor and updated to API V9 for me as I wasn't going to be able to get around to it until mid-November/early December. So just waiting for their changes to be approved now:

https://github.com/goatcorp/DalamudPluginsD17/pull/2573/

**Comment by GiacomoLaw** [comment]
Awesome thanks very much both :D
