### ISSUE TITLE
[Whitelist Suggestion] Keyboard commands for misc. volume controls

### ISSUE THREAD

**Issue by cc12138030** [NadyaNayme/TidyChat#8]
When controlling volume through the chat window, an option to still receive the output

/mastervolume -> "Master volume muted." / "Master volume unmuted."
/mastervolume # -> "Master volume set to #."
/bgm -> "BGM volume muted." / "BGM volume unmuted."
/bgm # -> "BGM volume set to #."
/soundeffects -> "Sound effects volume muted." / "Please tell me you've noticed the pattern."
/soundeffects # -> "I wonder what the output would be."
/voice -> "Voice volume blah blah blah"
/voice # -> "I bet this one is different. Oh it's not? What a surprise."
/systemsounds -> "Okay, I'm not typing out any more."
/systemsounds #
/ambientsounds
/ambientsounds #
/performsounds
/performsounds #

/mountbgm -> "Mount BGM volume muted." / "Mount BGM volume unmuted." (/mountbgm does not have a # command)

I guess any other potentially useful commands someone might think of.

Thanks.

**Comment by NadyaNayme** [comment]
I'm letting the 0.0.2.9 PR sit for a day or two after it gets approved to make sure it didn't release any additional bugs but these will be included in 0.0.2.10 as an optional whitelist in the new settings for the General tab under "Spam" Messages.
