### ISSUE TITLE
[FILTER] Add Mooch filter in fishing

### ISSUE THREAD

**Issue by cc12138030** [NadyaNayme/TidyChat#80]
## Filter Request

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**
"You recast your line with the fish still hooked."

**When does this message happen?**
After casting with a moochable fish.

**Why is it important to see this message?**
Certain plugins require this line to appear for their functionality, especially for timing purposes.

I have been completely unable to whitelist this line manually. No matter what I do it remains filtered.

**Comment by cc12138030** [comment]
Or this line could also just be included in the already available option "Show name of fishing hole when line is cast".

**Comment by NadyaNayme** [comment]
Was this related to or fixed by https://github.com/Ottermandias/GatherBuddy/pull/220 by any chance?

I can add the filter but that it hasn't been an issue until very recently makes me think it was related to the recent changes from ChatMessage --> ChatMessageHandled.

**Comment by cc12138030** [comment]
After reading that post that does seem to be the issue that is happening, but it doesn't look like there has been an update on GatherBuddy's end yet. There may be one in the works, but I'm not sure. Either way, it seems like the root cause has been determined, so you can proceed or ignore this in whichever direction you see fit.

**Comment by NadyaNayme** [comment]
It should be included in the next release - although I'm not 100% sure if it is a fix or not as I'm a bit removed from Dalamud developments as of the past year or so. 

For now I ask you either disable the Gathering filter, add a custom filter for the Gathering channel of `/recast your line with the fish/` (with the `/`'s so it gets parsed as a Regex) which _should_ work. 

If the next Gatherbuddy release doesn't fix the issue I'll absolutely go in and add the new filter for it.

**Comment by cc12138030** [comment]
Unfortunately that custom filter doesn't work, not sure why. I tried to set up custom filters before, including a regex version. Either way, the main Gathering filter works fine, and multiple people are aware of this new chat message hook, so it'll get sorted out eventually.

**Comment by NadyaNayme** [comment]
Hey - so a recent fix to custom filters for the Gathering channel was applied. I was filtering "GatheringSystem" and not "Gathering" channel for custom filters. My apologies.

Cstom filter should now work - but I'll also be adding a setting in the 2.0 rewrite as well.

**Comment by NadyaNayme** [comment]
Added to Tidy Chat 2.0 as a new filter

![image](https://github.com/user-attachments/assets/00927b7d-584c-4451-bf05-b5af43c95f1a)
