### ISSUE TITLE
[FILTER] /? <command> output get blocked by default

### ISSUE THREAD

**Issue by lilyremigia** [NadyaNayme/TidyChat#90]
## Filter Request

**What is the exact in-game message? A screenshot is fine but copy/paste is preferred.**
These are various, so finding them might be trickier, but I mean these kinds:
![kép](https://github.com/user-attachments/assets/f9dfcac6-0c29-4837-86bd-64a9ba3d2f91)

**When does this message happen?**
`/? <command>`
For example `/? ?` gives the following:
![kép](https://github.com/user-attachments/assets/b3092729-c34a-43d6-a1bd-072e71b975dd)

**Why is it important to see this message?**
If people are using this command, they  will usually want to see their output.

**Comment by NadyaNayme** [comment]
Using /? Is meant to disable Tidy Chat entirely for just a few seconds to let those messages go through so I'll investigate as to why this broke.

**Comment by NadyaNayme** [comment]
This will be fixed in 2.0.10. 

It will probably be on Monday as I need to resolve a framerate issue (#92) and I'm not sure if I'll be able to investigate that issue sooner.
